# docker image containing Developlement Tools and the current Intel compilers based on CentOS 7
image: iffregistry.fz-juelich.de/docker-images/centos7-intel-compilers


before_script:
  # set +e prevents sourced scripts from aborting if single commands fail (GitLab CI sets `-e` by default)
  - set +e && source compilervars.sh intel64 && set -e
  ## install pip
  #- curl -O https://bootstrap.pypa.io/get-pip.py 
  #- python get-pip.py 
  #- pip install numpy
  # set environment variables to avoind stack size issue
  - export OMP_NUM_THREADS=1
  - export OMP_STACKSIZE=1g
  - ulimit -s unlimited


stages:
  - test
  - build
  - run
  - verify


test:intel:
  stage: test
  script:
    # test if dependencies are working
    - echo 'do some tests here'

build:intel:mpi-aiida:
  stage: build
  script:
    # compile code
    - cp tests/inc.p_1 inc.p
    - make clean; make mpi; cp kkr.x kkr.x_1_mpi
  artifacts:
    paths:
      - kkr.x_1_mpi
    expire_in: 1 day


run:intel:aiida-kkr:
  image: iffregistry.fz-juelich.de/docker-images/aiida-kkr:latest
  stage: run
  services:
    - name: postgres:latest
      alias: db
    - name: iffregistry.fz-juelich.de/docker-images/centos7-intel-compilers/slurm-daemon:latest
      alias: c1
    - name: iffregistry.fz-juelich.de/docker-images/centos7-intel-compilers/slurm-daemon:latest
      alias: c2
    - name: iffregistry.fz-juelich.de/docker-images/centos7-intel-compilers/slurm-daemon:latest
      alias: c3
    - name: iffregistry.fz-juelich.de/docker-images/centos7-intel-compilers/slurm-daemon:latest
      alias: c4
  variables:
    POSTGRES_USER: aiida
    POSTGRES_DB: aiida_default
    POSTGRES_PASSWORD: password
  script:
    # some prepararion
    - umask 000 # needed to ensure that all subdirs created by aiida have the right permissions
    - cp kkr.x_1_mpi "${KKR_EXECUTABLE_PATH}" # copy kkr executable to correct dir
    - export C_FORCE_ROOT='true' # needed since root process executes aiida
    - verdi devel setproperty logging.celery_loglevel INFO && verdi devel setproperty logging.aiida_loglevel INFO && verdi daemon restart # restart aiida daemon with increased loglevel
    # compile latest voronoi version and add to aiida
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@iffgit.fz-juelich.de/kkr/voronoi.git voronoi
    - cd voronoi/prog/ && make && cd ../../
    - verdi code setup < "tests/tools/setup_voronoi_aiida.txt" 
    # finally run simple test case using kkr_scf workflow of aiida
    - tests/tools/aiida_simple_test.py
    # check some output of the calculation and export aiida database
    - verdi work report 6
    - verdi export create -n 6 -a tar.gz test_export.aiida.tar.gz
    # copy log file to include in artifacts
    - cp /root/.aiida/daemon/log/celery.log .
    - cp test_export.aiida.tar.gz /builds/kkr/aiida_run/
    - tar -zcvf aiida_run.tar.gz /builds/kkr/aiida_run/
  artifacts:
    paths:
      - aiida_run.tar.gz
      - celery.log
      - test_export.aiida.tar.gz
    expire_in: 2 day


verify:intel:aiida:
  image: iffregistry.fz-juelich.de/docker-images/aiida-kkr:latest
  stage: verify
  services:
    - name: postgres:latest
      alias: db
    - name: iffregistry.fz-juelich.de/docker-images/centos7-intel-compilers/slurm-daemon:latest
      alias: c1
    - name: iffregistry.fz-juelich.de/docker-images/centos7-intel-compilers/slurm-daemon:latest
      alias: c2
    - name: iffregistry.fz-juelich.de/docker-images/centos7-intel-compilers/slurm-daemon:latest
      alias: c3
    - name: iffregistry.fz-juelich.de/docker-images/centos7-intel-compilers/slurm-daemon:latest
      alias: c4
  variables:
    POSTGRES_USER: aiida
    POSTGRES_DB: aiida_default
    POSTGRES_PASSWORD: password
  script:
    # check some output of the calculation
    - verdi import test_export.aiida.tar.gz
    - python tests/tools/aiida_check_results.py
    
