# docker image containing Developlement Tools and the current Intel compilers based on CentOS 7
image: iffregistry.fz-juelich.de/docker-images/centos7-intel-compilers


before_script:
  # set +e prevents sourced scripts from aborting if single commands fail (GitLab CI sets `-e` by default)
  - set +e && source compilervars.sh intel64 && set -e
  # install pip
  - curl -O https://bootstrap.pypa.io/get-pip.py 
  - python get-pip.py 
  - pip install numpy
  # set environment variables to avoind stack size issue
  - export OMP_NUM_THREADS=1
  - export OMP_STACKSIZE=1g
  - ulimit -s unlimited


stages:
  - run
  - verify


###############################################################################

run:intel:rhoq_15:
  stage: run
  script:
    - mkdir tests/test_run15 && cd tests/test_run15 && ln -s ../test_inputs/test_15_*/* .
    - ./prepare.sh
    - ./run.sh
  artifacts:
    paths:
      - tests/test_run*
    expire_in: 2 days


###############################################################################
### 3. check outcome of the test runs ###

verify:intel:
  stage: verify
  script:
    # use pip to install pytest
    - pip install pytest
    # prepare and execute verification using pytest
    - cd tests
    - pytest -v --ignore=tools/aiida_simple_test.py 
