# docker image containing Developlement Tools and the current Intel compilers based on CentOS 7
image: iffregistry.fz-juelich.de/docker-images/centos7-intel-compilers

before_script:
  # set +e prevents sourced scripts from aborting if single commands fail (GitLab CI sets `-e` by default)
  - set +e && source compilervars.sh intel64 && set -e

stages:
  - build
  - run
  - verify

build:intel:
  stage: build
  script:
    # compile code
    - cp tests/inc.p .
    - make 
  artifacts:
    paths:
      - kkr.x
    expire_in: 1 day

run:intel:
  stage: run
  script:
    # set environment variables to avoind stack size issue
    - export OMP_NUM_THREADS=1
    - export OMP_STACKSIZE=1g
    - ulimit -s unlimited
    - cd tests
    - ./run_all.sh
  artifacts:
    paths:
      - tests/test_run*
    expire_in: 2 days

verify:intel:
  stage: verify
  script:
    # install pip
    - curl -O https://bootstrap.pypa.io/get-pip.py 
    - python get-pip.py 
    # use pip to install pytest
    - pip install numpy pytest
    # prepare and execute verification using pytest
    - cd tests
    - pytest -v

