rm -rf test_case_kkrflex_host_in_host/imp/test_run_mpi_1
rm -rf test_case_kkrflex_host_in_host/imp/test_run_mpi_8
rm -rf test_case_kkrflex_host_in_host/imp/test_run_hybrid_1_1
rm -rf test_case_kkrflex_host_in_host/imp/test_run_hybrid_1_8
rm -rf test_case_kkrflex_host_in_host/imp/test_run_hybrid_8_1
rm -rf test_case_kkrflex_host_in_host/imp/test_run_hybrid_2_4
rm -rf test_case_kkrflex_host_in_host/imp/test_run_hybrid_4_2
rm -rf test_case_kkrflex_host_in_host/imp/test_run_tmatnew_hybrid_2_4
rm -rf test_case_kkrflex_host_in_host/imp/test_run_tmatnew_mpi_8
rm -rf test_case_kkrflex_host_in_host/imp/test_run_nosavewf/out
rm -rf test_case_kkrflex_host_in_host/imp/test_run_nosratrick/out
rm -rf test_case_kkrflex_host_in_host/imp/test_run_Jij/out
rm -rf test_case_kkrflex_host_in_host/imp/test_run_Jij_savewf/out
rm -rf test_case_kkrflex_host_in_host/imp/test_run_Jij_nosratrick/out
