C ======================================================================
C   parameters file for the host TBKKR package -- TB-clusters settings
C                                          last update:   05/06/2004
C ======================================================================
C 
C     Description of parameters follows below (have to be set by hand
C     before compilation)
C ======================================================================
C
C PARAMETER   MEANING (settings)
C ----------------------------------------------------------------------
C NCLSD        maximum number of different TB-clusters
C NACLSD       maximum number of atoms in a TB-cluster
C
C ======================================================================
      INTEGER NCLSD, NACLSD
C
      PARAMETER ( NCLSD = 1)
      PARAMETER ( NACLSD = 249  )
C ======================================================================
