SHELL = /bin/sh

# Compiler and options
FC = ifort

########################################################################
#                          Executable
########################################################################

scoef_maker: 
		$(FC) -o scoef_maker.exe scoef_maker.F90

