      SUBROUTINE VXCDRV(EXC,KTE,KXC,LPOT,NSPIN,NSTART,NEND,RHO2NS,VONS,
     +                  R,DRDI,A,IRWS,IRCUT,IPAN,NTCELL,KSHAPE,GSH,ILM,
     +                  IMAXSH,IFUNM,THETAS,LMSP)
      IMPLICIT NONE
      INCLUDE 'inc.p'
C     .. Parameters ..
      INTEGER IJD,LMPOTD,LMXSPD
      PARAMETER (LMPOTD= (LPOTD+1)**2,LMXSPD= (2*LPOTD+1)**2)
      PARAMETER (IJD = 434)
C     ..
C     .. Scalar Arguments ..
      INTEGER KSHAPE,KTE,KXC,LPOT,NEND,NSPIN,NSTART
C     ..
C     .. Array Arguments ..
      DOUBLE PRECISION A(NATYPD),DRDI(IRMD,*),EXC(0:LPOTD,*),GSH(*),
     +                 R(IRMD,*),RHO2NS(IRMD,LMPOTD,NATYPD,*),
     +                 THETAS(IRID,NFUND,*),VONS(IRMD,LMPOTD,*)
      INTEGER IFUNM(NATYPD,*),ILM(NGSHD,3),IMAXSH(0:LMPOTD),IPAN(*),
     +        IRCUT(0:IPAND,*),IRWS(*),LMSP(NATYPD,*),NTCELL(*)
C     ..
C     .. External Subroutines ..
      EXTERNAL DCOPY,SPHERE_GGA,SPHERE_NOGGA,VXCGGA,VXCLM
C     ..
C     .. Local Arrays ..
      DOUBLE PRECISION DYLMF1(IJD,LMPOTD),DYLMF2(IJD,LMPOTD),
     +                 DYLMT1(IJD,LMPOTD),DYLMT2(IJD,LMPOTD),
     +                 DYLMTF(IJD,LMPOTD),RHO2IAT(IRMD,LMPOTD,2),
     +                 RIJ(IJD,3),THET(IJD),WTYR(IJD,LMPOTD),
     +                 YLM(IJD,LMPOTD),YR(IJD,LMPOTD)
      INTEGER IFUNMIAT(LMXSPD),LMSPIAT(LMXSPD)
C     ..
C     .. Local Scalars ..
      INTEGER IATYP,ICELL,IPOT,LMX1
C     ..
      IF (KXC.LT.3) THEN
        CALL SPHERE_NOGGA(LPOT,YR,WTYR,RIJ,IJD)
      ELSE
        CALL SPHERE_GGA(LPOT,YR,WTYR,RIJ,IJD,LMPOTD,THET,YLM,DYLMT1,
     +                  DYLMT2,DYLMF1,DYLMF2,DYLMTF)
      END IF
      DO IATYP = NSTART,NEND
        ICELL = NTCELL(IATYP)
        IPOT = NSPIN* (IATYP-1) + 1
        DO LMX1 = 1,LMXSPD
          IFUNMIAT(LMX1) = IFUNM(ICELL,LMX1)
          LMSPIAT(LMX1) = LMSP(ICELL,LMX1)
        END DO
        CALL DCOPY(IRMD*LMPOTD,RHO2NS(1,1,IATYP,1),1,RHO2IAT(1,1,1),1)
        IF (NSPIN.EQ.2 .OR. KREL.EQ.1) THEN
          CALL DCOPY(IRMD*LMPOTD,RHO2NS(1,1,IATYP,2),1,RHO2IAT(1,1,2),1)
        END IF
        IF (KXC.LT.3) THEN
          CALL VXCLM(EXC,KTE,KXC,LPOT,NSPIN,IATYP,RHO2IAT,
     +               VONS(1,1,IPOT),R(1,IATYP),DRDI(1,IATYP),
     +               IRWS(IATYP),IRCUT(0,IATYP),IPAN(IATYP),
     +               KSHAPE,GSH,ILM,IMAXSH,IFUNMIAT,THETAS(1,1,ICELL),
     +               YR,WTYR,IJD,LMSPIAT)
        ELSE
c
c GGA EX-COR POTENTIAL
c
          CALL VXCGGA(EXC,KTE,KXC,LPOT,NSPIN,IATYP,RHO2IAT,
     +                VONS(1,1,IPOT),R(1,IATYP),DRDI(1,IATYP),A(IATYP),
     +                IRWS(IATYP),IRCUT(0,IATYP),IPAN(IATYP),
     +                KSHAPE,GSH,ILM,IMAXSH,IFUNMIAT,THETAS(1,1,ICELL),
     +                WTYR,IJD,LMSPIAT,THET,YLM,DYLMT1,DYLMT2,
     +                DYLMF1,DYLMF2,DYLMTF)
        END IF
      END DO
      END
